### ISSUE TITLE
Re-work Coverflow Viewtype

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#304]
It's large and horribly clunky to make changes to.

**Comment by jingai** [comment]
MacGyver's reimagining of it is sitting on the coverflow branch.

**Comment by MacGyverr** [comment]
Can Kodi do math yet?  If so, then you could scale up and down the size depending on the number of objects in a list.  You can do it now without, but it would require having 9 full list renders that are visible only when size=1,2,3,4,5,...  
So the big thing is can it do math with variables yet in order to set size and placement?

**Comment by jingai** [comment]
I don't see it in the list of skin changes for either Helix or I*******, so I presume no :(
