### ISSUE TITLE
Make the music playlist menu look more like the other Metropolis menus

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#335]
https://github.com/MacGyverr/Metropolis/commit/e81e6ad6f63180e4453c33079fa27140f8227776

https://github.com/MacGyverr/Metropolis/commit/a38de962f94ec2f2564510236e96593ecd92b1d9

**Comment by jingai** [comment]
Also this, will need to look it all over:

https://github.com/MacGyverr/skin.metropolis-personal/commit/25f1033cb939dbc4b6fe615815c4506ae17f9318

**Comment by jingai** [comment]
@MacGyverr, you have a fixme left in one of those commits.  Is there a finished product for this?

**Comment by MacGyverr** [comment]
The final file should be ok, there is a "fake" comment just to remind me that everything below that is there just so that menu looks that way.  It works fie as is, but I think it can be reworked to be much much smaller, at the time I didn't see a smaller way and just wanted to commit it.   Most of that code I think can be removed, but at the cost of it looking the exact same.

**Comment by jingai** [comment]
So the one on your Isengard branch is the one to use?

https://github.com/MacGyverr/skin.metropolis-personal/blob/isengard/720p/MyMusicPlaylist.xml
