### ISSUE TITLE
Consider using script.skinshortcuts templates

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#358]
Particularly for widgets.

https://github.com/Ignoble61/script.skinshortcuts/blob/documentation/resources/docs/advanced/Templates.md

**Comment by MacGyverr** [comment]
Hypothetically speaking, what would happen if skinshortcuts was to become disabled once you are using templates?  I never really saw a big problem using it to create the menus because that happens once (and I always put a prebuilt one in there just in case). If it breaks here or there no big deal, users may not be able to setup custom menus in the interim and only use the ones they have already created, but if large pieces of the skin are going to be relying on it always being 100% working you might want to see just what happens to that version in the event skinshortcuts gets broken (or disabled) before letting it loose on the users.

**Comment by jingai** [comment]
Discuss over here now please https://github.com/jingai/skin.metropolis/issues/19

Moved to my own repo.
